name: Docs

on:
  workflow_run:
    workflows: ["Lint"]
#    branches:
#      - main
    types:
      - completed
#      - closed # https://github.community/t/depend-on-another-workflow/16311/3

jobs:
  on-success:
    if:
      ${{ github.event.workflow_run.conclusion == 'success' }} || github.event.pull_request.merged
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx sphinx_rtd_theme sphinx-copybutton

      - name: Build documentation
        working-directory: docs
        run:  make html

      - name: Copy static files
        run: |
          mv .nojekyll static/html
          mv logo_skmob.png static/html
          mv coverage static/html

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: .
