name: Documentation Build

on: [push, pull_request]
#on:
#  push:
#    paths:
#      - "docs/**"
#      - "README.md"
#      - "skmob/**"
#  pull_request:
#    paths:
#      - "docs/**"
#      - "README.md"
#      - "skmob/**"

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install sphinx sphinx_rtd_theme sphinx-copybutton

      - name: Build documentation
        working-directory: docs
        run:  make html

      - name: Copy static files
        run: |
          mv .nojekyll static
          mv logo_skmob.png static

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.1
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: static/html # The folder the action should deploy.
