name: Lint

on: [push, pull_request]

jobs:
  build:
    # We want to run on external PRs, but not on our own internal PRs as they'll be run
    # by the push to the branch. Without this if check, checks are duplicated since
    # internal PRs match both the push and pull_request events.
    if:
      github.event_name == 'push' || github.event.pull_request.head.repo.full_name !=
      github.repository

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.6

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --upgrade pre-commit pytest coverage tox

      - name: Lint
        run: pre-commit run --show-diff-on-failure --files  skmob/tessellation

      - name: Test and Test Coverage
        run: |
          coverage run -m pytest skmob/tessellation
          coverage html
          mv .coverage coverage
